"""courier delivery

Revision ID: 6293a99b0b9c
Revises: ced74685a439
Create Date: 2026-09-24 21:01:52.662493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6293a99b0b9c'
down_revision: Union[str, Sequence[str], None] = 'ced74685a439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_couriers')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_couriers_telegram_id'))
    )
    op.create_table('courier_locations',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_courier_locations_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_courier_locations_longitude_range')),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name=op.f('fk_courier_locations_courier_id_couriers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('courier_id', name=op.f('pk_courier_locations'))
    )
    op.add_column('shipments', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # courier_id was a plain integer with nothing ever writing to it; clear it defensively so the
    # new foreign key cannot fail on a stray value.
    op.execute("UPDATE shipments SET courier_id = NULL WHERE courier_id IS NOT NULL")
    op.create_foreign_key(op.f('fk_shipments_courier_id_couriers'), 'shipments', 'couriers', ['courier_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_shipments_courier_id_status', 'shipments', ['courier_id', 'status'], unique=False)
    op.create_index('ix_shipments_status', 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Return to the previous schema's vocabulary first: it has no 'assigned' shipment status, so
    # loading such a row would fail there. Put those orders back in the pool ('paid').
    op.execute(
        "UPDATE orders SET status = 'paid' "
        "WHERE id IN (SELECT order_id FROM shipments WHERE status = 'assigned')"
    )
    op.execute("UPDATE shipments SET status = 'processing' WHERE status = 'assigned'")
    # The couriers table is about to disappear, so leave no dangling references behind.
    op.execute("UPDATE shipments SET courier_id = NULL")
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.drop_index('ix_shipments_courier_id_status', table_name='shipments')
    op.drop_constraint(op.f('fk_shipments_courier_id_couriers'), 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'delivered_at')
    op.drop_column('shipments', 'picked_up_at')
    op.drop_column('shipments', 'assigned_at')
    op.drop_table('courier_locations')
    op.drop_table('couriers')
    # ### end Alembic commands ###
