"""admin panel

Revision ID: bbb147ebf681
Revises: 6293a99b0b9c
Create Date: 2026-09-24 22:15:47.378608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb147ebf681'
down_revision: Union[str, Sequence[str], None] = '6293a99b0b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'catalog_manager', 'dispatcher', name='adminrole', native_enum=False, length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_admins_telegram_id'))
    )
    op.add_column('orders', sa.Column('stock_shortfall', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('refund_status', sa.Enum('pending', 'succeeded', 'failed', name='refundstatus', native_enum=False, length=20), nullable=True))
    op.add_column('payments', sa.Column('stripe_refund_id', sa.String(length=255), nullable=True))
    op.add_column('product_images', sa.Column('storage_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The previous schema has no 'cancelled' shipment status and could not load such a row. The
    # order itself stays 'cancelled' (a status that schema knows), so the shipment carries nothing.
    op.execute("DELETE FROM shipments WHERE status = 'cancelled'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'storage_key')
    op.drop_column('payments', 'stripe_refund_id')
    op.drop_column('payments', 'refund_status')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'cancelled_by')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'stock_shortfall')
    op.drop_table('admins')
    # ### end Alembic commands ###
